name: Mirroring

on: [push, delete]

jobs:
  to_codeberg:
    runs-on: ubuntu-latest
    steps:                  
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url:
            git@codeberg.org:LuaLink/LuaLinkV2.git
          ssh_private_key:                             
            ${{ secrets.THE_MACHINE_PRIV }}
